### PR TITLE
doc: Adding initial version of README.md (with how to create an effective issue report)

### PR DESCRIPTION
**Pull request by czp13**
## Description

Adding some text/thoughts about how to create an effective, useful, and clear issue report.

## Type of change

- [ ] Bugfix
- [x] Feature

## Checklist

- [x] I have read the contribution guide: https://vaadin.com/docs/latest/guide/contributing/overview/
- [x] I have added a description following the guideline.
- [x] The issue is created in the corresponding repository and I have referenced it.
- [x] I have added tests to ensure my change is effective and works as intended.
- [x] New and existing tests are passing locally with my change.
- [x] I have performed self-review and corrected misspellings.

#### Additional for `Feature` type of change

- [x] Enhancement / new feature was discussed in a corresponding GitHub issue and Acceptance Criteria were created.

### CODE REVIEW

**Comment by MarcinVaadin** [comment]
I think it would be easier to create issue template rather than describe all steps in readme.

**Comment by czp13** [comment]
> I think it would be easier to create issue template rather than describe all steps in readme.
Can we do both? :D 

Or shall I push these changes to the git template?

**Comment by MarcinVaadin** [comment]
I cannot modify issue template @Artur- please update permissions

**Comment by Artur-** [comment]
Try now

**Comment by MarcinVaadin** [comment]
I still don't see them, they should be in "Issues" which I don't have https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by czp13** [comment]
Works for me!
image

**Pull request merged**
